config/routes.rb
Rails.application.routes.draw do

  resources :categories

  scope "(:locale)", locale: /en|it|en-GB/ do
    devise_for :users
    resources :listings do
      resources :orders, only: [:new, :create]
    end

    get 'pages/about'
    get 'pages/contact'
    get 'seller' => "listings#seller"
    get 'sales' => "orders#sales"
    get 'purchases' => "orders#purchases"

    root 'listings#index'
  end

end

app/views/layouts/_footer.html.erb
<br>
<!-- <p>© Stephan Musgrave 2014</p> -->

<!-- Ruby method to get current year-->
<!-- <p>© Stephan Musgrave <%#= Time.now.year %></p> -->

<!-- JavaScript method to get current year: needs manual page refresh-->
<p>© Ratna Musgrave
  <span id="current_year"></span>
</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to "SolIndia", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to t('navbar.about'), pages_about_path %></li>
        <li><%= link_to t('navbar.contact'), pages_contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('navbar.language') %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t('navbar.us_english'), root_path(locale: 'en') %></li>
            <li><%= link_to t('navbar.gb_english'), root_path(locale: 'en-GB') %></li>
            <li><%= link_to t('navbar.italian'), root_path(locale: 'it') %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse<b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, listings_path(category: category.name) %></li>
            <% end %>
          </ul>
        </li>

      </ul>
       <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('navbar.seller_account') %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t('navbar.manage_my_listings'), seller_path %></li>
              <li><%= link_to t('navbar.sales_history'), sales_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
              <%= link_to purchases_path do %>
                <i class="glyphicon glyphicon-folder-open"></i>&nbsp;&nbsp;<%= t('navbar.purchase_history') %><br>
              <% end %>
              <%= link_to edit_user_registration_path do %>
                <i class="glyphicon glyphicon-wrench"></i>&nbsp;&nbsp;<%= t('navbar.edit_profile') %><br>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="glyphicon glyphicon-log-out"></i>&nbsp;&nbsp;<%= t('navbar.sign_out') %><br>
              <% end %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('navbar.sign_up'), new_user_registration_path %></li>
          <li><%= link_to t('navbar.sign_in'), new_user_session_path %></li>
        <% end %>
       </ul>
    </div><!-- /'navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EtsyDemo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etsydemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>

<body>
  <%= render 'layouts/header' %>
  
  <div class="container">

    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>

  <%= render 'layouts/footer' %>

</div>

</body>
</html>